export { default as About } from './About'
export { default as Banner } from './Banner'
export { default as Contact } from './Contact'
export { default as Feature } from './Feature'
export { default as Login } from './Login'
export { default as WeOffer } from './WeOffer'
